format = """
$sudo\
${custom.python_version}\
$directory\
$git_branch$git_status\
$character\
"""

right_format = """
$docker_context\
$package\
${custom.machine}\
$time\
"""

add_newline = true

[line_break]
disabled = false

[fill]
symbol = " "

[username]
style_user = "bright-yellow bold"
style_root = "bright-red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
disabled = true

[character]
success_symbol = "[➜](bold cyan)"
error_symbol = "[➜](bold red)"

[directory]
format = "[$path](bold cyan)"
truncation_length = 1
truncation_symbol = ""
home_symbol = "~"
# read_only = " "

[git_branch]
symbol = "[](fg:black)[](fg:red bg:black)"
style = "fg:red bg:black"
format = '[$symbol $branch]($style)'

[git_status]
untracked = "[ •](fg:yellow bg:black)"
modified = "[ •](fg:cyan bg:black)"
staged = "[ •](fg:green bg:black)"
deleted = "[ •](fg:red bg:black)"
ahead = "[ ↑](fg:yellow bg:black)"
behind = "[ ↓](fg:yellow bg:black)"
diverged = "[ 󰦻](fg:cyan bg:black)"
conflicted = "[ ⊘](fg:red bg:black)"
stashed = ""
typechanged = ""
renamed = ""
up_to_date = ""
format = '$all_status$ahead_behind[](fg:black)'

[time]
disabled = false
time_format = "%R"
style = "fg:green bg:black"
format = '[](fg:black)[$time]($style)[](fg:black)'

[custom.machine]
description = "Machine label from STARSHIP_MACHINE_LABEL env var"
command = 'echo "${STARSHIP_MACHINE_LABEL:-$(hostname -s)}"'
when = "true"
format = "[](fg:black)[$output](fg:red bg:black)[](fg:black)"

[custom.python_version]
description = "putting the python verion in the prompt"
command = "echo \"$(python --version | awk '{split($2, a, \".\"); print a[1] \".\" a[2]}')\""
when = '[[ -n "$VIRTUAL_ENV" ]]'
format = "[](fg:black)[ ](fg:yellow bg:black)[$output](fg:green bg:black)[](fg:black)"

[custom.venv]
description = "putting the python venv symbol in the prompt if there is a venv active"
command = 'echo ""'
when = '[[ -n "$VIRTUAL_ENV" ]]'
style = "fg:yellow"
format = " [$output]($style)"

[package]
format = "[\\($version\\)](fg:#ff6900)"
disabled = true

[docker_context]
symbol = " "
format = "[$symbol](cyan)"

[nodejs]
symbol = " "
format = "[$symbol $version]"

[os]
format = "[$symbol]($style)"
style = "bold yellow dimmed"
disabled = false

[os.symbols]
Macos = " "
Linux = " "
Windows = " "


[sudo]
style = 'bold yellow'
symbol = ''
format = "[$symbol]($style)"
disabled = true
